const mongoose=require('mongoose');

const testSchema = mongoose.Schema(
    {
        tname:{
            type:String,
            required:true,
        },
        //id is generated by default
        amount:{
            type: Number,
            required: true,
        },
        date:{
            type:String,
            required: true,
        },
        duration:{
            type: Number,
            required: true,
        },
        needPayment: {
            type: Boolean,
            required: true,
        },
        start_time:{
            type: String,
            required: true,
        },
        state:{
            type:String,
            required:true,
        },
       
        totalMarks:{
            type:Number,
            required:true,
        },
        pid:{
            type:mongoose.SchemaTypes.ObjectId,
            required:true,
        },
        uid:{
            type:mongoose.SchemaTypes.ObjectId,
            required:true,
        },       
    },
    {
        timestamps:true,
    }
);


const Test=mongoose.model("Test",testSchema);

module.exports=Test;